name: Deploy Dokploy

on:
  workflow_run:
    workflows: ["Build and Push Streamlit Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Chamar deploy no Dokploy
        run: curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}"